= Vert.x- Vertx-Practice

Here you will find examples demonstrating Vert.x-Web in action.

Vert.x-Web is a tool-kit for writing web applications with Vert.x. Please consult the Vert.x-Web manual for detailed
documentation on Vert.x-Web.


== Dependencies required

To use Vert.x-Web in your own Maven project you will need following dependencies

----
Group ID: io.vertx
Artifact ID: vertx-core
----

and

----
Group ID: io.vertx
Artifact ID: vertx-web
----


== Vertex-Practice Web-service

Vert.x-Web is a great fit for HTTP/REST web-services.

Here's a simple web-service example which implements an API for a image list functionality.

The link:src/main/java/io/vertx/example/web/rest/Server.java

The API allows you to extract the image list from external url and send the response to front end.

Image list is provided in JSON array.

List all images:: GET http://localhost:8443


Run the server either in your IDE or on the command line, then open your browser and hit
link:http://localhost:8443 to start playing with the API.


== Front End -- Html and Angularjs

This example shows a basic single page application built with Angular JS.

A very simple html page is created to show the images in the middle of the page according to the image id.

-- on the top of image:
       -- Album id, image id and title is given


== To compile the project and get jar file

   -- run "mvn package" command in terminal and a jar file named
       as Vertx-Practice-3.6.1.jar will be created in target folder.


